version: "3.4"

services:
  apistub:
    image: ${DOCKER_REGISTRY-}apistub
    build:
      context: .
      dockerfile: BankApi/ApiStub/Dockerfile
    ports:
      - "52053:80"
    environment:
      WireMockServerSettings__Urls: "['http://localhost:80']"

  paymentgateway:
    image: ${DOCKER_REGISTRY-}paymentgateway
    build:
      context: .
      dockerfile: PaymentGateway/Dockerfile
    depends_on:
      - "apistub"
    ports:
      - "52054:80"
    environment:
      bank-api-options__ApiProtocol: "http"
      bank-api-options__ApiHost: "host.docker.internal:52053"
      bank-api-options__AuthApiHost: "host.docker.internal:52053"
